# BlueOS - drivers/nvme/host/Makefile

obj-y += drivers/nvme/host/core.o \
         drivers/nvme/host/ioctl.o \
         drivers/nvme/host/lightnvm.o \
         drivers/nvme/host/multipath.o \
         drivers/nvme/host/pci.o