obj-y += irq.o keyboard_io.o apic.o kvm.o timer.o shell.o intel.o acpi.o \
		 amd.o interrupts-a.o gdt.o gdt-a.o virt.o cmdline.o vmm.o elf.o \
		 userspace_a.o loader.o arch.o syscall.o boot.o panic.o interrupts.o \
		 interrupt_entry.o profile.o switch.o bg.o syscall.o idt.o