obj-y += kernel/posix/sys_open.o \
		 kernel/posix/sys_read.o \
		 kernel/posix/sys_write.o \
		 kernel/posix/sys_close.o \
		 kernel/posix/sys_fork.o \
		 kernel/posix/sys_execve.o \
		 kernel/posix/sys_wait4.o \
		 kernel/posix/sys_exit.o \
		 kernel/posix/sys_mmap.o \
		 kernel/posix/sys_brk.o \
		 kernel/posix/sys_mprotect.o \
		 kernel/posix/sys_stat.c \
		 kernel/posix/sys_chmod.o \
		 kernel/posix/sys_chown.o
