obj-y += kernel/userspace.o \
         kernel/vmcore_info.o \
         kernel/time.o \
         kernel/task.o \
         kernel/sysctl.o \
         kernel/sched.o \
         kernel/printk.o \
         kernel/ping.o \
         kernel/module.o \
         kernel/hpet.o \
         kernel/hlec.o \
         kernel/sys.o \
         kernel/bluefetch.o \
         kernel/exec.o \
         kernel/run_user.o \
         kernel/lkm.o \
         kernel/security.o \
         kernel/process.o \
         kernel/stack_protector.o