obj_y += leds/leds.o vhost/vhost_net.o rtc/rtc.o battery/battery.o net/virtio_net.o \
		 isapnp/isapnp.o video/vt220.o video/vt100.o bcma/bcma.o ata/ata.o amba/amba_pl011.o \
	     connector/connector.o i2c/i2c.o thermal/lm75.o soc/soc_intel.o pnp/pnp.o hyperv/hypervisor.o \
		 core/live_config.o cdrom/cdrom.o gpio/gpio.o input/joystick/ps3/ps3_ds3.o input/mouse/8042/mouse.o \
		 input/keyboard/8042/keyboard.o input/keyboard/kbd_common.o scsi/scsi_core.o scsi/scsi_lsi.o 