#include <drivers/vt100.h>
#include <kernel/colors.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define MAX_CONFIGS 128

typedef struct {
  char *name;
  char *prompt;
  char *type;
  int value; /* 0 = off/no, 1 = on/yes */
} kconfig_option_t;

kconfig_option_t config_db[MAX_CONFIGS];
int config_count = 0;
int current_selection = 0;

/* Mock internal function representing the lexer stream invocation */
void mock_parse_kconfig() {
  config_db[0] = (kconfig_option_t){
      "CONFIG_RISCV_MMU", "Enable RISC-V Memory Management Unit", "bool", 1};
  config_db[1] = (kconfig_option_t){
      "CONFIG_PCI_MSI", "Support Message Signaled Interrupts (MSI)", "bool", 0};
  config_db[2] = (kconfig_option_t){
      "CONFIG_USB_UHCI", "UHCI 1990s Classic Controller Driver", "bool", 1};
  config_db[3] =
      (kconfig_option_t){"CONFIG_SOUND_BLASTER",
                         "Sound Blaster 16 ISA Architecture Driver", "bool", 0};
  config_db[4] = (kconfig_option_t){
      "CONFIG_DEBUG_LKDTM", "Linux Kernel Dump Test Module (LKDTM)", "bool", 1};
  config_count = 5;
}

void draw_menu() {
  /* Clear terminal screen using clean legacy VT100 controls */
  printf("\033[2J\033[H");
  printf("\033[36m============================================================="
         "======\033[0m\n");
  printf(
      "            BlueOS Kernel Configuration Utility (Kconfig)          \n");
  printf("\033[36m============================================================="
         "======\033[0m\n\n");
  printf(" Use [Arrow Keys] or j/k to navigate, [Space] to toggle, [Enter] to "
         "Save.\n\n");

  for (int i = 0; i < config_count; i++) {
    if (i == current_selection) {
      /* Highlight selected active row line */
      printf("  \033[44m\033[37m-> [%c] %s (%s)\033[0m\n",
             config_db[i].value ? '*' : ' ', config_db[i].prompt,
             config_db[i].name);
    } else {
      printf("     [%c] %s (%s)\n", config_db[i].value ? '*' : ' ',
             config_db[i].prompt, config_db[i].name);
    }
  }
  printf("\n\033[36m-----------------------------------------------------------"
         "--------\033[0m\n");
}

void save_config() {
  FILE *fp = fopen(".config", "w");
  if (!fp) {
    printf("Error: Cannot write runtime target .config metadata file.\n");
    return;
  }
  fprintf(fp,
          "# Automatically generated by BlueOS mconf utility. Do not edit.\n");
  for (int i = 0; i < config_count; i++) {
    if (strcmp(config_db[i].type, "bool") == 0) {
      if (config_db[i].value) {
        fprintf(fp, "%s=y\n", config_db[i].name);
      } else {
        fprintf(fp, "# %s is not set\n", config_db[i].name);
      }
    }
  }
  fclose(fp);
  printf("\n\033[32m[ SUCCESS ] Configuration saved successfully to '.config' "
         "file!\033[0m\n");
}

int main(int argc, char **argv) {
  /* Load default simulated or parsed options database definitions */
  mock_parse_kconfig();

  /* Disable canonical echo line buffering modes on compatible terminal
   * configurations */
  system("stty -icanon -echo");

  int running = 1;
  while (running) {
    draw_menu();
    char c = getchar();

    /* Process keystroke mappings matching suckless styling choices */
    if (c == 'k' || c == 'A') { /* Up navigation */
      if (current_selection > 0)
        current_selection--;
    } else if (c == 'j' || c == 'B') { /* Down navigation */
      if (current_selection < config_count - 1)
        current_selection++;
    } else if (c ==
               ' ') { /* Spacebar toggles standard boolean hardware values */
      config_db[current_selection].value = !config_db[current_selection].value;
    } else if (c ==
               '\n') { /* Enter exits loop and triggers code saving routine */
      running = 0;
    }
  }

  /* Restore pristine terminal properties back to host systems */
  system("stty icanon echo");
  save_config();

  return 0;
}