import sys

def generate_header(config_file, header_file):
    with open(config_file, 'r') as f:
        lines = f.readlines()

    with open(header_file, 'w') as f:
        f.write("/* Auto-generated by BlueOS Build System */\n")
        f.write("#ifndef BLUEOS_CONFIG_H\n")
        f.write("#define BLUEOS_CONFIG_H\n\n")

        for line in lines:
            line = line.strip()
            if not line or line.startswith('#'):
                continue

            key, val = line.split('=')
            if val == 'y':
                f.write(f"#define {key} 1\n")
            elif val == 'n':
                f.write(f"#undef {key}\n")
            else:
                f.write(f"#define {key} {val}\n")

        f.write("\n#endif\n")

if __name__ == "__main__":
    generate_header('.config', 'include/config.h')
