obj-y += crypto/sha256.o \
		 crypto/des.o \
		 crypto/md5.o \
		 crypto/chacha20.o \
		 crypto/blowfish.o \
		 crypto/sha1.o \
		 crypto/zstd.o \
		 crypto/sha512.o \
		 crypto/lz4.o \
		 crypto/gzip.o